// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using finance_api.Data;

#nullable disable

namespace finance_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260110014311_PlaidIntegration")]
    partial class PlaidIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("finance_api.Models.Budget", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoryId")
                        .HasColumnType("int");

                    b.Property<int>("limit")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("categoryId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("finance_api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Bills",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transport",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pleasure",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Food",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shopping",
                            TransactionType = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Salary",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Investment",
                            TransactionType = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pets",
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("finance_api.Models.RecurringTransactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("RecurringTransactions");
                });

            modelBuilder.Entity("finance_api.Models.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Electricity"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Water"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Gas"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Public Transport"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Uber"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Gas"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Cinema"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Golf"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Skateboard"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Name = "Soccer"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Name = "Concerts"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            Name = "Dining Out"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 7,
                            Name = "Stocks"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 7,
                            Name = "Interest"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 8,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 8,
                            Name = "Litter"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 8,
                            Name = "Vet"
                        });
                });

            modelBuilder.Entity("finance_api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("finance_api.Plaid.PlaidItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlaidItems");
                });

            modelBuilder.Entity("finance_api.Models.Budget", b =>
                {
                    b.HasOne("finance_api.Models.Category", "category")
                        .WithMany()
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("finance_api.Models.RecurringTransactions", b =>
                {
                    b.HasOne("finance_api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("finance_api.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("finance_api.Models.SubCategory", b =>
                {
                    b.HasOne("finance_api.Models.Category", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("finance_api.Models.Transaction", b =>
                {
                    b.HasOne("finance_api.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("finance_api.Models.SubCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId");

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("finance_api.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
